---
experiment:
  name: co-cge-ow/mitstates/
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
  open_world: true
model_params:
  model: graphfull
  dropout: true
  norm: true
  nlayers: 
  gr_emb: d600
  emb_dim: 512
  emb_init: ft+w2v
  image_extractor: resnet18
  train_only: false
  cosine_classifier: true
  feasibility_adjacency: true
  relu: true
training:
  batch_size: 128
  eval_val_every: 2
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.4
  cosine_scale: 20
  max_epochs: 200
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  epoch_max_margin: 15
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_features: false
  is_wandb: False
  split_loss: False
  pair_unmatch: False
  split_unmatch: False
  multilabel: False
  temp: 1
